config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :books

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true,length: { maximum: 50 }
  validates :body, presence: true,length: { maximum: 140 }

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    if @book.save
     redirect_to book_path(@book.id)
    else
      render :index
    end
    flash[:notice] = "Book was successfully created."
  end

  def edit
     @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
     redirect_to book_path(@book.id)
     flash[:notice] = "Book was successfully updated."
    else
      render:edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book, url: "/books/#{@book.id}", method: :put,local:true do |f| %>
  <label for="book_title">Title</label>
    <%= f.text_field :title %>
  <label for="book_body">Body</label>
    <%= f.text_area :body %>

  <%= f.submit "Update Book" %>

  <% end %>

  <div>  <%= link_to "show",book_path(@book)%> |
   <%= link_to "back",books_path%>
  </div>
  <% if @book.errors.any? %>
     <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

app/views/books/index.html.erb
<body>
  <p id="notice"></p>
  <h1>Books</h1>
  <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
     <tr>
       <td><%= book.title %></td>
       <td><%= book.body %></td>
       <td><%= link_to "Show",book_path(book.id)%></td>
       <td><%= link_to "Edit",edit_book_path(book.id)%></td>
       <td><%= link_to "Destroy",book_path(book.id),method: :delete,"data-confirm"=>"Are you sure?"%></td>



     </tr>


    <% end %>
    </ui>
  <% if @book.errors.any? %>
     <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ui>
  <% end %>

  </tbody>
</table>
<h2>New book</h2>
<%= form_with model: @book, url: '/books', method: :post,local:true do |f| %>
  <label for="book_title">Title</label>
  <%= f.text_field :title %>

  <label for="book_body">Body</label>
  <%= f.text_area :body %>

  <%= f.submit "Create Book" %>

<% end %>
</body>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>

<p><strong>Title:</strong>
　<%= @book.title %>
</p>

<p><strong>body:</strong>
　<%= @book.body %>
</p>

 <%= link_to "Edit",edit_book_path(@book)%>|
 <%= link_to "Back",books_path %>
</div>

app/views/homes/top.html.erb
<head>
　<title>WebCampBackendNew</title>
　<meta name="csrf-param" content="authenticity_token">
　<meta name="csrf-token" content="YqiqOh3Kpuz32fVl8WhzEodn+gjXiUMTJf1ynEgM8qodNecmVzvp+Y4GXDYGuQx+W6+6BpJBPUrb1FwvBUEuIQ==">
　<link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload">
　<script src="/assets/application-114264dd93c8ff30e4335b71eed7949d66c4e7a8eb62e2de6284c046fe07104b.js" data-turbolinks-track="reload"></script>
</head>

<body>
  <h1>
    ようこそ"
    <strong>Bookers</strong>
    へ！
  </h1>
  <p>
    <strong>Bookers</strong>
      では、さまざまな書籍に関するあなたの意見や
  </p>
  <p>印象を共有し交換することができます</p>
  <p>
    <a href="/books">start</a>
  </p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>